blank_issues_enabled: true
contact_links:
  - name: Documentación del proyecto
    url: https://github.com/Grant-Thornton-Costa-Rica/.github/wiki
    about: Consulta la documentación del proyecto antes de crear un nuevo issue.